### PR TITLE
fixed SA crash.

### PR DESCRIPTION
**Pull request by gknisely**
@dgearhart @dnesbitt61 @kevinkreiser

### CODE REVIEW

**Comment by kevinkreiser** [comment]
any chance for a description on this? what will happen when we encounter a restriction that looks like:

"Mo-Fr 07:00-18:10"

**Comment by gknisely** [comment]
It will pass now.  The above was for a bus route and the data is entered incorrectly.

**Comment by gknisely** [comment]
Both fields should have data.  day_on and day_off

**Comment by kevinkreiser** [comment]
so this data is poorly tagged and will be ignored?

**Comment by gknisely** [comment]
yes sir

**Comment by kevinkreiser** [comment]
:sheep: it

**Comment by dgearhart** [comment]
:+1:

**Pull request merged**
