### PR TITLE
transitioning from cyclelanes to cycleway gets stop impact of 0.

### PR DESCRIPTION
**Pull request by gknisely**
@dnesbitt61 does this make sense to you.  Could anything get broken?

Fixes: https://github.com/valhalla/conf/issues/27

screenshot from 2015-12-08 15 52 56
screenshot from 2015-12-08 15 22 46

### CODE REVIEW

**Comment by kevinkreiser** [comment]
it sounds intuitive except for when crossing non cycle paths

**Comment by dnesbitt61** [comment]
yea, this doesn't look right

**Comment by gknisely** [comment]
What should it be then

**Comment by gknisely** [comment]
https://github.com/valhalla/sif/pull/77 actually fixes https://github.com/valhalla/conf/issues/27

**Pull request closed without merging**
